id: I9638BEF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T16:57:14+00:00'
last_modified: '2022-06-10T08:55:27.326170+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16713
  title: དཔེ་ཝར་མཆོག་སྤྲུལ་འཇམ་དབྱངས་བསོད་ནམས་དབང་པོའི་གསན་ཡིག་འདོད་རྒུའི་བང་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    641D:
      image_group_id: I2PD18102
      title: Volume 1 of dpe war mchog sprul 'jam dbyangs bsod nams dbang po'i gsan
        yig 'dod rgu'i bang mdzod/
      total_pages: 594
      order: 1
      base_file: 641D.txt
    '5447':
      image_group_id: I2PD18103
      title: Volume 2 of dpe war mchog sprul 'jam dbyangs bsod nams dbang po'i gsan
        yig 'dod rgu'i bang mdzod/
      total_pages: 506
      order: 2
      base_file: 5447.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
